spring: 
  profiles: 
    active:
    - dev

---
spring: 
  profiles: dev
  application:
    name: microservice-gateway

server: 
  port: 6001

eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka4001.com:4001/eureka,http://eureka4002.com:4002/eureka,http://eureka4003.com:4003/eureka  
  instance:
    instance-id: gateway.com
    prefer-ip-address: true 
---
spring: 
  profiles: test
  application:
    name: microservice-gateway

server: 
  port: 6011

 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka4001.com:4001/eureka,http://eureka4002.com:4002/eureka,http://eureka4003.com:4003/eureka  
  instance:
    instance-id: gateway.com
    prefer-ip-address: true 

---
spring: 
  profiles: prov
  application:
    name: microservice-gateway

server: 
  port: 6021

eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka4001.com:4001/eureka,http://eureka4002.com:4002/eureka,http://eureka4003.com:4003/eureka  
  instance:
    instance-id: gateway.com
    prefer-ip-address: true 

