spring: 
  profiles: 
    active:
    - dev

---
spring: 
  profiles: dev
  
  
server: 
  port: 8901
  
eureka: 
  client: 
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka4001.com:4001/eureka/,http://eureka4002.com:4002/eureka/,http://eureka4003.com:4003/eureka/
---
spring: 
  profiles: test


server: 
  port: 8911
  
eureka: 
  client: 
    register-with-eureka: false
    service-url: 
      defaultZone: http://eureka4001.com:4001/eureka/,http://eureka4002.com:4002/eureka/,http://eureka4003.com:4003/eureka/
---
spring: 
  profiles: prov


server: 
  port: 8921
  
eureka:
  client:   
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka4001.com:4001/eureka/,http://eureka4002.com:4002/eureka/,http://eureka4003.com:4003/eureka/