spring:
  profiles:
    active: 
    - dev
    
---
server: 
  port: 4001 #注册中心占用7001端口，冒号后面必须要有空格

spring:
  profiles: dev
  application:
    name: microservice-eureka-4001
    
eureka:
  instance:
    hostname: eureka4001.com #冒号后面必须要有空格
  client:
    register-with-eureka: false #单签的Eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过Eureka获取注册信息
    service-url:
      defaultZone: http://eureka4001.com:4001/eureka/
      
---
server: 
  port: 4001 #注册中心占用7001端口，冒号后面必须要有空格

spring:
  profiles: test
  application:
    name: microservice-eureka-4001
    
eureka:
  instance:
    hostname: eureka4001.com #冒号后面必须要有空格
  client:
    register-with-eureka: false #单签的Eureka-server自己不注册进服务列表中
    fetch-registry: false #不通过Eureka获取注册信息
    service-url:
      defaultZone: http://eureka4001.com:4001/eureka/
